-- ShopFlow baseline schema. All primary keys are uuid, generated by the application.
-- Every table carries created_at / updated_at as timestamptz.

-- ---------------------------------------------------------------- auth

CREATE TABLE roles (
    id         uuid         PRIMARY KEY,
    code       varchar(30)  NOT NULL,
    name       varchar(100) NOT NULL,
    created_at timestamptz  NOT NULL,
    updated_at timestamptz  NOT NULL,
    CONSTRAINT uq_roles_code UNIQUE (code)
);

CREATE TABLE users (
    id             uuid         PRIMARY KEY,
    email          varchar(255) NOT NULL,
    password_hash  varchar(255) NOT NULL,
    full_name      varchar(255) NOT NULL,
    phone          varchar(30),
    status         varchar(20)  NOT NULL,
    email_verified boolean      NOT NULL DEFAULT false,
    created_at     timestamptz  NOT NULL,
    updated_at     timestamptz  NOT NULL
);

-- Case-insensitive uniqueness: two accounts cannot differ only by email casing.
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));

CREATE TABLE user_roles (
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id uuid NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE addresses (
    id                  uuid         PRIMARY KEY,
    user_id             uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    recipient_name      varchar(255) NOT NULL,
    phone               varchar(30),
    line1               varchar(255) NOT NULL,
    line2               varchar(255),
    city                varchar(120) NOT NULL,
    state               varchar(120),
    postal_code         varchar(20)  NOT NULL,
    country             varchar(2)   NOT NULL,
    is_default_shipping boolean      NOT NULL DEFAULT false,
    is_default_billing  boolean      NOT NULL DEFAULT false,
    created_at          timestamptz  NOT NULL,
    updated_at          timestamptz  NOT NULL
);

CREATE INDEX idx_addresses_user_id ON addresses (user_id);

-- token_hash is a SHA-256 hex digest: 64 characters. The raw token is never stored.
CREATE TABLE refresh_tokens (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  varchar(64) NOT NULL,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    replaced_by uuid        REFERENCES refresh_tokens (id),
    user_agent  varchar(255),
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id         uuid        PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_password_reset_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

-- user_id is nullable: a failed login for an unknown email still has to be recorded.
CREATE TABLE auth_events (
    id         uuid        PRIMARY KEY,
    user_id    uuid        REFERENCES users (id) ON DELETE SET NULL,
    event_type varchar(40) NOT NULL,
    ip_address varchar(45),
    user_agent varchar(255),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE INDEX idx_auth_events_user_id ON auth_events (user_id);
CREATE INDEX idx_auth_events_created_at ON auth_events (created_at);

-- ---------------------------------------------------------------- catalog

CREATE TABLE categories (
    id          uuid          PRIMARY KEY,
    name        varchar(255)  NOT NULL,
    code        varchar(100)  NOT NULL,
    description varchar(2000),
    created_at  timestamptz   NOT NULL,
    updated_at  timestamptz   NOT NULL,
    CONSTRAINT uq_categories_code UNIQUE (code)
);

CREATE TABLE category_types (
    id          uuid          PRIMARY KEY,
    category_id uuid          NOT NULL REFERENCES categories (id),
    name        varchar(255)  NOT NULL,
    code        varchar(100)  NOT NULL,
    description varchar(2000),
    created_at  timestamptz   NOT NULL,
    updated_at  timestamptz   NOT NULL
);

CREATE INDEX idx_category_types_category_id ON category_types (category_id);

CREATE TABLE products (
    id               uuid          PRIMARY KEY,
    name             varchar(255)  NOT NULL,
    description      varchar(2000),
    price            numeric(12,2) NOT NULL,
    category_id      uuid          NOT NULL REFERENCES categories (id),
    category_type_id uuid          NOT NULL REFERENCES category_types (id),
    created_at       timestamptz   NOT NULL,
    updated_at       timestamptz   NOT NULL
);

CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_category_type_id ON products (category_type_id);

CREATE TABLE product_variants (
    id             uuid        PRIMARY KEY,
    product_id     uuid        NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    color          varchar(60),
    size           varchar(30),
    stock_quantity integer     NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL,
    updated_at     timestamptz NOT NULL
);

CREATE INDEX idx_product_variants_product_id ON product_variants (product_id);

CREATE TABLE product_resources (
    id         uuid          PRIMARY KEY,
    product_id uuid          NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    name       varchar(255),
    url        varchar(1000) NOT NULL,
    type       varchar(30),
    is_primary boolean       NOT NULL DEFAULT false,
    created_at timestamptz   NOT NULL,
    updated_at timestamptz   NOT NULL
);

CREATE INDEX idx_product_resources_product_id ON product_resources (product_id);
