/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a customer account and return a token pair */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and return a new token pair */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset token; always accepted
         * @description Returns 202 whether or not the email is registered, so the endpoint cannot be used to discover which addresses have accounts.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume a reset token, set a new password, and end every session */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the presented refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and return a token pair */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's orders, newest first */
        get: operations["listOrders"];
        put?: never;
        /**
         * Place an order from the cart
         * @description Empties the cart and takes the stock. Answers 409 when the cart is empty or an item is no longer in stock, and 404 for an address that is not the caller's.
         */
        post: operations["placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/orders/{orderId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay for an order
         * @description Answers 402 when the charge is declined, leaving the order payable, and 409 when the order is not awaiting payment.
         */
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an unpaid order
         * @description Returns the stock to the catalogue. A paid order answers 409: reversing a completed sale is a refund, which is not part of this API yet.
         */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add units to the cart
         * @description Merges into the existing line when the variant is already in the cart. Answers 409 when the resulting quantity exceeds available stock.
         */
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's addresses, oldest first */
        get: operations["list"];
        put?: never;
        /** Create an address for the authenticated user */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/variants/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust a variant's stock by a signed delta
         * @description The row is locked for update, so an adjustment cannot be computed from a stale read while a checkout is in flight. A result below zero answers 409. reason is required and is written to the audit trail.
         */
        post: operations["adjustStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/variants/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore an archived variant
         * @description Idempotent.
         */
        post: operations["restoreVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products for administration
         * @description Excludes archived products unless archived=only or archived=all. Each row carries the unarchived variant count and total stock.
         */
        get: operations["listProducts"];
        put?: never;
        /**
         * Create a product
         * @description The category type must belong to the category, or the answer is 404.
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a variant to a product
         * @description stockQuantity is an opening balance and defaults to zero. Later changes go through the stock endpoint.
         */
        post: operations["createVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore an archived product
         * @description Does not resurrect variants archived separately. Idempotent.
         */
        post: operations["restoreProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a resource to a product
         * @description isPrimary defaults to false. Setting it true demotes the product's current primary in the same transaction.
         */
        post: operations["createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}/ship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a paid order shipped
         * @description PAID only; anything else answers 409. trackingReference is required.
         */
        post: operations["shipOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a shipped order delivered
         * @description SHIPPED only; anything else answers 409. DELIVERED is terminal.
         */
        post: operations["deliverOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an unpaid order and return its stock
         * @description PENDING_PAYMENT only. Cancelling a paid order would be a refund, which this API does not implement, so it answers 409.
         */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a category
         * @description Answers 409 when the code is already taken.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{id}/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a type to a category
         * @description The code must be unique within the category.
         */
        post: operations["createCategoryType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user's profile */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the authenticated user's name or phone
         * @description Omitted or null fields are left unchanged. An empty phone clears it. Email, roles, status and password cannot be changed here.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/me/cart/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a line from the cart */
        delete: operations["removeItem"];
        options?: never;
        head?: never;
        /**
         * Set a line's quantity
         * @description A line belonging to another user answers 404, not 403.
         */
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/me/addresses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one of the authenticated user's addresses */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * Update one of the authenticated user's addresses
         * @description Omitted or null fields are left unchanged. An empty string clears an optional field. An address belonging to another user answers 404, not 403.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/admin/variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Archive a variant
         * @description Sets archivedAt rather than deleting the row, so live carts and order history survive. Idempotent.
         */
        delete: operations["archiveVariant"];
        options?: never;
        head?: never;
        /**
         * Update a variant's colour or size
         * @description Stock is not patchable; use the stock endpoint.
         */
        patch: operations["updateVariant"];
        trace?: never;
    };
    "/api/admin/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a resource
         * @description A hard delete, unlike products and variants: nothing snapshots a resource. No replacement primary is promoted.
         */
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        /**
         * Update a resource
         * @description Partial: an omitted field is left unchanged. Promoting one to primary demotes the others.
         */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/api/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One product, including archived rows
         * @description Unlike the public endpoint, an archived product answers 200 rather than 404, and archived variants are included.
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /**
         * Archive a product
         * @description Sets archivedAt rather than deleting the row, so order history and live carts survive. Idempotent.
         */
        delete: operations["archiveProduct"];
        options?: never;
        head?: never;
        /**
         * Update a product
         * @description Partial: an omitted field is left unchanged.
         */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/api/admin/category-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a category type
         * @description Answers 409 while any product still references it.
         */
        delete: operations["deleteCategoryType"];
        options?: never;
        head?: never;
        /**
         * Update a category type
         * @description Partial. A type cannot be moved to another category.
         */
        patch: operations["updateCategoryType"];
        trace?: never;
    };
    "/api/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a category and its types
         * @description Answers 409 while any product still references it.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /**
         * Update a category
         * @description Partial: an omitted field is left unchanged. The code is immutable.
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProductById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One order in full
         * @description Another user's order answers 404, not 403.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated user's cart
         * @description Returns an empty cart rather than 404 when nothing has been added yet.
         */
        get: operations["getCart"];
        put?: never;
        post?: never;
        /** Empty the cart */
        delete: operations["clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders for administration
         * @description Filters by status, customer, order number, and placement window. from is inclusive and to is exclusive.
         */
        get: operations["listOrders_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One order, whoever placed it
         * @description Includes the customer's identity and the fulfilment fields, neither of which appears on the customer-facing shape.
         */
        get: operations["getOrder_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the admin audit trail
         * @description Newest first. Filters by target, acting administrator, and action. Events are never written or deleted through the API.
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
            phone?: string;
        };
        TokenPairResponse: {
            accessToken?: string;
            refreshToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirmRequest: {
            token: string;
            newPassword: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        PlaceOrderRequest: {
            /** Format: uuid */
            shippingAddressId: string;
        };
        OrderItemResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            productId?: string;
            /** Format: uuid */
            variantId?: string;
            productName?: string;
            color?: string;
            size?: string;
            unitPrice?: number;
            /** Format: int32 */
            quantity?: number;
            lineTotal?: number;
        };
        OrderResponse: {
            /** Format: uuid */
            id?: string;
            orderNumber?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "PAID" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            currency?: string;
            subtotalAmount?: number;
            totalAmount?: number;
            shippingAddress?: components["schemas"]["ShippingAddressResponse"];
            items?: components["schemas"]["OrderItemResponse"][];
            /** Format: date-time */
            placedAt?: string;
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
        };
        ShippingAddressResponse: {
            recipientName?: string;
            phone?: string;
            line1?: string;
            line2?: string;
            city?: string;
            state?: string;
            postalCode?: string;
            country?: string;
        };
        PayOrderRequest: {
            paymentMethodToken: string;
        };
        AddCartItemRequest: {
            /** Format: uuid */
            variantId: string;
            /** Format: int32 */
            quantity: number;
        };
        CartItemResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            productId?: string;
            productName?: string;
            thumbnail?: string;
            /** Format: uuid */
            variantId?: string;
            color?: string;
            size?: string;
            unitPrice?: number;
            /** Format: int32 */
            quantity?: number;
            lineTotal?: number;
            /** Format: int32 */
            availableStock?: number;
        };
        CartResponse: {
            items?: components["schemas"]["CartItemResponse"][];
            subtotal?: number;
            /** Format: int32 */
            totalQuantity?: number;
        };
        CreateAddressRequest: {
            recipientName: string;
            phone?: string;
            line1: string;
            line2?: string;
            city: string;
            state?: string;
            postalCode: string;
            country: string;
            defaultShipping?: boolean;
            defaultBilling?: boolean;
        };
        AddressResponse: {
            /** Format: uuid */
            id?: string;
            recipientName?: string;
            phone?: string;
            line1?: string;
            line2?: string;
            city?: string;
            state?: string;
            postalCode?: string;
            country?: string;
            defaultShipping?: boolean;
            defaultBilling?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        AdjustStockRequest: {
            /** Format: int32 */
            delta: number;
            reason: string;
            deltaNonZero?: boolean;
        };
        StockAdjustmentResponse: {
            /** Format: uuid */
            variantId?: string;
            /** Format: int32 */
            previousQuantity?: number;
            /** Format: int32 */
            newQuantity?: number;
            /** Format: int32 */
            delta?: number;
            reason?: string;
        };
        AdminVariantResponse: {
            /** Format: uuid */
            id?: string;
            color?: string;
            size?: string;
            /** Format: int32 */
            stockQuantity?: number;
            /** Format: date-time */
            archivedAt?: string;
        };
        CreateProductRequest: {
            name: string;
            description?: string;
            price: number;
            /** Format: uuid */
            categoryId: string;
            /** Format: uuid */
            categoryTypeId: string;
        };
        AdminProductResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            price?: number;
            /** Format: uuid */
            categoryId?: string;
            categoryName?: string;
            /** Format: uuid */
            categoryTypeId?: string;
            categoryTypeName?: string;
            /** Format: date-time */
            archivedAt?: string;
            variants?: components["schemas"]["AdminVariantResponse"][];
            resources?: components["schemas"]["ProductResourceDto"][];
        };
        ProductResourceDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            url?: string;
            type?: string;
            isPrimary?: boolean;
        };
        CreateVariantRequest: {
            color: string;
            size: string;
            /** Format: int32 */
            stockQuantity?: number;
        };
        CreateResourceRequest: {
            name?: string;
            url: string;
            type?: string;
            isPrimary?: boolean;
        };
        ShipOrderRequest: {
            trackingReference: string;
        };
        AdminOrderResponse: {
            /** Format: uuid */
            id?: string;
            orderNumber?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "PAID" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            /** Format: uuid */
            userId?: string;
            userEmail?: string;
            currency?: string;
            subtotalAmount?: number;
            totalAmount?: number;
            paymentReference?: string;
            trackingReference?: string;
            shippingAddress?: components["schemas"]["ShippingAddressResponse"];
            items?: components["schemas"]["OrderItemResponse"][];
            /** Format: date-time */
            placedAt?: string;
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            shippedAt?: string;
            /** Format: date-time */
            deliveredAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
        };
        CreateCategoryRequest: {
            name: string;
            code: string;
            description?: string;
        };
        CategoryResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            description?: string;
            types?: components["schemas"]["CategoryTypeResponse"][];
        };
        CategoryTypeResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            description?: string;
        };
        CreateCategoryTypeRequest: {
            name: string;
            code: string;
            description?: string;
        };
        UpdateProfileRequest: {
            fullName?: string;
            phone?: string;
        };
        UserProfileResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            fullName?: string;
            phone?: string;
            emailVerified?: boolean;
            roles?: string[];
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateCartItemRequest: {
            /** Format: int32 */
            quantity: number;
        };
        UpdateAddressRequest: {
            recipientName?: string;
            phone?: string;
            line1?: string;
            line2?: string;
            city?: string;
            state?: string;
            postalCode?: string;
            country?: string;
            defaultShipping?: boolean;
            defaultBilling?: boolean;
        };
        UpdateVariantRequest: {
            color?: string;
            size?: string;
        };
        UpdateResourceRequest: {
            name?: string;
            url?: string;
            type?: string;
            isPrimary?: boolean;
        };
        UpdateProductRequest: {
            name?: string;
            description?: string;
            price?: number;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            categoryTypeId?: string;
        };
        UpdateCategoryTypeRequest: {
            name?: string;
            description?: string;
        };
        UpdateCategoryRequest: {
            name?: string;
            description?: string;
        };
        PageResponseProductSummaryResponse: {
            content?: components["schemas"]["ProductSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        ProductSummaryResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            price?: number;
            thumbnail?: string;
            /** Format: uuid */
            categoryId?: string;
            categoryName?: string;
            /** Format: uuid */
            categoryTypeId?: string;
            categoryTypeName?: string;
        };
        ProductDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            price?: number;
            thumbnail?: string;
            /** Format: uuid */
            categoryId?: string;
            categoryName?: string;
            /** Format: uuid */
            categoryTypeId?: string;
            categoryTypeName?: string;
            variants?: components["schemas"]["ProductVariantDto"][];
            productResources?: components["schemas"]["ProductResourceDto"][];
        };
        ProductVariantDto: {
            /** Format: uuid */
            id?: string;
            color?: string;
            size?: string;
            /** Format: int32 */
            stockQuantity?: number;
        };
        OrderSummaryResponse: {
            /** Format: uuid */
            id?: string;
            orderNumber?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "PAID" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            currency?: string;
            totalAmount?: number;
            /** Format: date-time */
            placedAt?: string;
        };
        PageResponseOrderSummaryResponse: {
            content?: components["schemas"]["OrderSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        AdminProductSummaryResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            price?: number;
            thumbnail?: string;
            /** Format: uuid */
            categoryId?: string;
            categoryName?: string;
            /** Format: uuid */
            categoryTypeId?: string;
            categoryTypeName?: string;
            /** Format: int64 */
            variantCount?: number;
            /** Format: int64 */
            totalStock?: number;
            /** Format: date-time */
            archivedAt?: string;
        };
        PageResponseAdminProductSummaryResponse: {
            content?: components["schemas"]["AdminProductSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        AdminOrderSummaryResponse: {
            /** Format: uuid */
            id?: string;
            orderNumber?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "PAID" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            /** Format: uuid */
            userId?: string;
            userEmail?: string;
            currency?: string;
            totalAmount?: number;
            /** Format: date-time */
            placedAt?: string;
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            shippedAt?: string;
            /** Format: date-time */
            deliveredAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
            trackingReference?: string;
        };
        PageResponseAdminOrderSummaryResponse: {
            content?: components["schemas"]["AdminOrderSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        AdminEventResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            actorUserId?: string;
            actorEmail?: string;
            /** @enum {string} */
            action?: "CATEGORY_CREATED" | "CATEGORY_UPDATED" | "CATEGORY_DELETED" | "CATEGORY_TYPE_CREATED" | "CATEGORY_TYPE_UPDATED" | "CATEGORY_TYPE_DELETED" | "PRODUCT_CREATED" | "PRODUCT_UPDATED" | "PRODUCT_ARCHIVED" | "PRODUCT_RESTORED" | "VARIANT_CREATED" | "VARIANT_UPDATED" | "VARIANT_ARCHIVED" | "VARIANT_RESTORED" | "STOCK_ADJUSTED" | "RESOURCE_CREATED" | "RESOURCE_UPDATED" | "RESOURCE_DELETED" | "ORDER_SHIPPED" | "ORDER_DELIVERED" | "ORDER_CANCELLED";
            /** @enum {string} */
            targetType?: "CATEGORY" | "CATEGORY_TYPE" | "PRODUCT" | "PRODUCT_VARIANT" | "PRODUCT_RESOURCE" | "ORDER";
            /** Format: uuid */
            targetId?: string;
            detail?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageResponseAdminEventResponse: {
            content?: components["schemas"]["AdminEventResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseOrderSummaryResponse"];
                };
            };
        };
    };
    placeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayOrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAddressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponse"];
                };
            };
        };
    };
    adjustStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustStockRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StockAdjustmentResponse"];
                };
            };
        };
    };
    restoreVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminVariantResponse"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: {
                archived?: string;
                categoryId?: string;
                q?: string;
                page?: number;
                size?: number;
                sort?: string;
                direction?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminProductSummaryResponse"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProductResponse"];
                };
            };
        };
    };
    createVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminVariantResponse"];
                };
            };
        };
    };
    restoreProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProductResponse"];
                };
            };
        };
    };
    createResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResourceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductResourceDto"];
                };
            };
        };
    };
    shipOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShipOrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    deliverOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    createCategoryType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryTypeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTypeResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAddressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponse"];
                };
            };
        };
    };
    archiveVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminVariantResponse"];
                };
            };
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductResourceDto"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProductResponse"];
                };
            };
        };
    };
    archiveProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProductResponse"];
                };
            };
        };
    };
    deleteCategoryType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCategoryType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryTypeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTypeResponse"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    listProducts_1: {
        parameters: {
            query?: {
                categoryId?: string;
                categoryTypeId?: string;
                q?: string;
                page?: number;
                size?: number;
                sort?: string;
                direction?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseProductSummaryResponse"];
                };
            };
        };
    };
    getProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    listOrders_1: {
        parameters: {
            query?: {
                status?: "PENDING_PAYMENT" | "PAID" | "SHIPPED" | "DELIVERED" | "CANCELLED";
                userId?: string;
                orderNumber?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
                sort?: string;
                direction?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminOrderSummaryResponse"];
                };
            };
        };
    };
    getOrder_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                targetType?: "CATEGORY" | "CATEGORY_TYPE" | "PRODUCT" | "PRODUCT_VARIANT" | "PRODUCT_RESOURCE" | "ORDER";
                targetId?: string;
                actorUserId?: string;
                action?: "CATEGORY_CREATED" | "CATEGORY_UPDATED" | "CATEGORY_DELETED" | "CATEGORY_TYPE_CREATED" | "CATEGORY_TYPE_UPDATED" | "CATEGORY_TYPE_DELETED" | "PRODUCT_CREATED" | "PRODUCT_UPDATED" | "PRODUCT_ARCHIVED" | "PRODUCT_RESTORED" | "VARIANT_CREATED" | "VARIANT_UPDATED" | "VARIANT_ARCHIVED" | "VARIANT_RESTORED" | "STOCK_ADJUSTED" | "RESOURCE_CREATED" | "RESOURCE_UPDATED" | "RESOURCE_DELETED" | "ORDER_SHIPPED" | "ORDER_DELIVERED" | "ORDER_CANCELLED";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminEventResponse"];
                };
            };
        };
    };
}
